# Generated by Django 5.0.7 on 2024-08-04 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
                ('subtype', models.CharField(max_length=20)),
                ('number', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('balance', models.FloatField()),
                ('currencyCode', models.CharField(max_length=6)),
                ('marketingName', models.CharField(blank=True, max_length=100, null=True)),
                ('owner', models.CharField(blank=True, max_length=100, null=True)),
                ('taxNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('age', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreditCardMetaData',
            fields=[
                ('transactionId', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('installmentNumber', models.BigIntegerField(blank=True, null=True)),
                ('totalInstallments', models.BigIntegerField(blank=True, null=True)),
                ('totalAmount', models.FloatField(blank=True, null=True)),
                ('payeeMCC', models.BigIntegerField(blank=True, null=True)),
                ('cardNumber', models.CharField(blank=True, max_length=60, null=True)),
                ('billId', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('transactionId', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('businessName', models.CharField(blank=True, max_length=200, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=20, null=True)),
                ('cnae', models.CharField(blank=True, max_length=20, null=True)),
                ('category', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('accountId', models.CharField(max_length=40)),
                ('date', models.DateTimeField()),
                ('tipo', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('descriptionRaw', models.TextField(blank=True, null=True)),
                ('currencyCode', models.CharField(max_length=6)),
                ('amount', models.FloatField()),
                ('balance', models.FloatField(blank=True, null=True)),
                ('amountInAccountCurrency', models.FloatField(blank=True, null=True)),
                ('category', models.TextField(blank=True, null=True)),
                ('categoryId', models.BigIntegerField(blank=True, null=True)),
                ('providerCode', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
